<a href="https://colab.research.google.com/github/Vashi1/Python-Projects/blob/master/Data_Science_In_Practice_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Encapsulation and Data Abstraction:**


**1. Create a class Student with attributes name (private), age (protected), and marks (public). Implement methods to set and get the values of the private and protected attributes. Create an instance of the class and demonstrate how to use these methods to access and modify the attributes.**

**2. Create a base class Shape with a protected attribute area. Implement subclasses Circle and Rectangle that calculate their respective areas. Make use of protected members to store and access the calculated areas.**

**3. Write a class Calculator that implements a method evaluate expression() to calculate the result of an arithmetic expression following the PEMDAS rule.**

**4. Create a program that reads data from a CSV file named data.csv containing student names and their scores. Implement a class Student with attributes name and score. Read the data from the CSV file and create instances of the Student class for each student. Compute the average for the class using a numpy function**



In [13]:
class Student:
  def __init__(self, name, age, marks):
    self.__name = 'Rakshith'
    self._age = 20
    self.marks = 100
  def set_name(self):
    self.__name = "Rakshith"
  def disp_name(self):
    print(self.__name)
  def set_age(self):
    self._age = 18
  def disp_age(self):
    print(self._age)
  def set_marks(self):
    self.marks = 99
  def disp_marks(self):
    print(self.marks)

a1 = Student("ARyan", 29, 89)
print(a1.marks)
a1.set_name()
a1.disp_name()
a1.set_age()
a1.disp_age()
a1.set_marks()
a1.disp_marks()

100
Rakshith
18
99


In [35]:
class Shape:
  def __init__(self):
    self._area = 100

class Circle(Shape):
  def __init__(self, radius):
    Shape.__init__(self)
    self.radius = radius
  def dis_area(self):
    self._area = 3.14 * self.radius ** 2
    print(self._area)


class Rectangle(Shape):
  def __init__(self, length, breadth):
    Shape.__init__(self)
    self.length = length
    self.breadth = breadth
  def dis_area(self):
    self._area = self.length * self.breadth
    print(self._area)


if __name__ == "__main__":
  C1 = Circle(10)
  C1.dis_area()
  R1 = Rectangle(10, 20)
  R1.dis_area()

314.0
200


In [ ]:
class Calculator:
  def __init__(self, opr1, opr2, exp):
    self.opr1 = opr1
    self.opr2 = opr2
    self.exp = exp
  def expression(self):
    if self.exp == "+":
      cal = self.opr1 + self.opr2
    elif self.exp == "-":
      cal = self.opr1 - self.opr2
    elif self.exp == "*":
      cal = self.opr1 * self.opr2
    elif self.exp == "/":
      if (self.opr2 == 0):
        return "Divide by Zero Error!"
      else:
        cal = self.opr1 / self.opr2
    return cal

s1 = Calculator(2, 3, '+')
a1 = s1.expression()
print(a1)

s2 = Calculator(10, 4, '/')
print(s2.expression())

5
2.5


Create a program that reads data from a CSV file named data.csv containing student names and their scores. Implement a class Student with attributes name and score. Read the data from the CSV file and create instances of the Student class for each student. Compute the average for the class using a numpy function

In [ ]:
import csv

**Welcome To Numpy**

This assignment will help you the explore the Numpy library and its various uses. It would also cover some use cases about how numpy makes Machine Learning and Data Science calculations easy and fast. This assignment is made in order to encourage you to explore more and more builtin functions of this library and their usage. For all problems, you need to print the output.




**Importing Numpy**

The first step involves importing Numpy so that you can start using it right away. There are a lot of ways to do so depending upon how you want to use library or some functions of it. In general, we import it all together and in order to avoid writing numpy again and again, we abbreviate it in some form. For ex. np. Import the Numpy library as np in the below cell.

In [ ]:
import numpy as np

**Arrays In Numpy**

As already discussed in class, there are various ways of making numpy arrays. In the below cells we would test your ability to implement them correctly.

**Create a numpy array of 1's of user defined dimensions**

Take input for 2 dimensions : N and M, create a 2D matrix of 1's. Note : In general you can make numpy arrays of any number of dimensions. eg. 3, 4, and so on...

In [ ]:
a = int(input("Enter the m dimension: "))
b = int(input("Enter the n dimension: "))
arr = np.ones((a, b))
print(arr)

Enter the m dimension: 5
Enter the n dimension: 5
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Create an empty array Using Numpy**

When you print your array, you might see random values in your array. Repeat instructions as mentioned for previous cell.


In [ ]:
a = int(input("Enter the m dimension: "))
b = int(input("Enter the n dimension: "))
arr1 =np.empty((a, b))
print(arr1)

Enter the m dimension: 4
Enter the n dimension: 3
[[4.88733083e-310 0.00000000e+000 6.78152382e-310]
 [6.78152383e-310 6.78152382e-310 6.78152383e-310]
 [6.78152383e-310 6.78152382e-310 6.78152383e-310]
 [6.78152382e-310 4.88618452e-310 6.78157890e-310]]


**Create a numpy array of 0's of user defined dimensions**

Repeat instructions as mentioned previously


In [ ]:
a = int(input("Enter the m dimension: "))
b = int(input("Enter the n dimension: "))
arr1 =np.zeros((a, b))
print(arr1)

Enter the m dimension: 4
Enter the n dimension: 4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Create a numpy array from numbers 1 to 10 using inbuilt functions**

This task can be implemented using 2 functions : **arange()** and **linspace()**. You have to make use of both of them in cells given below

In [ ]:
n1 = np.arange(1, 11, 1)
print(n1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
n2 = np.linspace(1, 10, 5)
print(n2)

[ 1.    3.25  5.5   7.75 10.  ]


**Convert a simple list to array**

Create a 1D list and a 2D list and convert them to numpy arrays. You need to print the type of both after conversion in order to check if they are really converted or not.

In [ ]:
l1 = [1, 2, 3, 4]
print("Type of l1: ", type(l1))
nx = np.asarray(l1)
print(nx)
print("Type of n1: ", type(nx))
l2 = [[1, 2, 3], [4, 5, 6]]
print("Type of l2: ", type(l2))
ny = np.asarray(l2)
print(ny)
print("type of n2", type(ny))

Type of l1:  <class 'list'>
[1 2 3 4]
Type of n1:  <class 'numpy.ndarray'>
Type of l2:  <class 'list'>
[[1 2 3]
 [4 5 6]]
type of n2 <class 'numpy.ndarray'>


**Conversion Of Data Types in Numpy arrays**

In this problem, you need to convert float numpy array to integer type and vice versa. You need to print the array after each conversion.

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
n_a = np.asarray(a)
print(n_a)
print(type(n_a[0][0]))

[[1 2 3]
 [4 5 6]]
<class 'numpy.int64'>


In [ ]:
a1 = np.ones((10, 10), dtype = np.float64)
print(a1)
print(type(n_a[0][0]))


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<class 'numpy.int64'>


**Given below is an array of 20 elements. Convert this array into 2D matrices of dimensions 1 x 20, 2 x 10, 4 x 5, 5 x 4, 10 x 2 and 20 x 1**

**For each given dimensions, you need to print the new array**

**For the 1 x 20 array, print every third element using indexing & slicing**

**Use the array splitter function for the 10 x 2 array having results with 3 elements**

**Concatenate arrays 10 x 2 and 20 x 1 using concatenate(), hstack(),vstack, dstack() or using axis values, you may combine reshape() for either arrays so that all the functions work, provide comments while you stack arrays for the reader to have clarity for the steps**

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [ ]:
a1 = np.reshape(a, (1, 20))
print(a1)
print(a1[0][: 20 : 3])

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
[ 1  4  7 10 13 16 19]


In [ ]:
a2 = np.reshape(a, (2, 10))
print(a2)
a3 = np.reshape(a, (4, 5))
print(a3)
a4 = np.reshape(a, (5, 4))
print(a4)
a5 = np.reshape(a, (10, 2))
print(a5)
a6 = np.reshape(a, (20, 1))
print(a6)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


**Use the array splitter function for the 10 x 2 array having results with 3 elements**

In [ ]:
import numpy as np

In [ ]:
l = np.array([[ 1,  2],[ 3,  4],[ 5,  6],[ 7,  8],[ 9, 10],[11, 12],[13, 14],[15, 16],[17, 18],[19, 20]])
a5_1 = np.array_split(l, 3)
for i in a5_1:
  print(i)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]
 [13 14]]
[[15 16]
 [17 18]
 [19 20]]


**Find maximum element in array and print its value and its index using numpy inbuilt functions**

In [ ]:
a = np.array([100,40,30,106,4589,2,34,76,9777,1023,56,62,395])

In [ ]:
ma = np.max(a)
print(ma)
l = np.where(ma)
print(l)

9777
(array([0]),)


**Print Dimensions Of The Given Array, shape of the array and size**

**Iterate through the array 'a' skipping a value and printing the next value.**

**Implement reshape on this array with your choice of parameters (not 1D)**

**Make a 1D array also and sort the array, then find the indices of values ==6 using numpy functions**

**On the 1D array, implement a numpy function to print values only above 100**



In [ ]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[7,8,9],[10,102,546]])
print('shape: ', np.shape(a))
print("size: ", np.size(a))

shape:  (5, 3)
size:  15


In [ ]:
s, _ = np.shape(a)
for i in range(0, s, 2):
  print(a[i])

[1 2 3]
[6 7 8]
[ 10 102 546]


In [ ]:
b1 = np.reshape(a, (5, 3))
print(b1)

[[  1   2   3]
 [  4   5   6]
 [  6   7   8]
 [  7   8   9]
 [ 10 102 546]]


In [ ]:
c1 = np.sort(a)
print(c1)
e1 = np.reshape(a, (15, ))
print("reshaped array: ", e1)
d1 = np.where(e1 == 6)
print(d1)

[[  1   2   3]
 [  4   5   6]
 [  6   7   8]
 [  7   8   9]
 [ 10 102 546]]
reshaped array:  [  1   2   3   4   5   6   6   7   8   7   8   9  10 102 546]
(array([5, 6]),)


In [ ]:
print(e1[e1 > 100])

[102 546]


**Create a NumPy array with the integers from your birthdate (year, month, and day)**

**Retrieve the year.**

**Replace the year with the current year**

**Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?**

In [ ]:
d0b = np.array([2003, 8, 5])
print(d0b)

[2003    8    5]


In [ ]:
year = d0b[0]
print(year)

2003


In [ ]:
d0b[0] = 2003
print(d0b)

[2003    8    5]


In [ ]:
n9 = np.arange(567, 890, 3)
print(n9)
print("The 8th and 15th elements are: ")
print(n9[7], n9[14])

[567 570 573 576 579 582 585 588 591 594 597 600 603 606 609 612 615 618
 621 624 627 630 633 636 639 642 645 648 651 654 657 660 663 666 669 672
 675 678 681 684 687 690 693 696 699 702 705 708 711 714 717 720 723 726
 729 732 735 738 741 744 747 750 753 756 759 762 765 768 771 774 777 780
 783 786 789 792 795 798 801 804 807 810 813 816 819 822 825 828 831 834
 837 840 843 846 849 852 855 858 861 864 867 870 873 876 879 882 885 888]
The 8th and 15th elements are: 
588 609


**Evaluate (PEMDAS):**
1. ((((12+7)*2)-4)/2)-13
2. 5+5/5
3. 2*5//4
4. 2\*\*3\*\*2
5. (2\*\*3)\*\*2

In [ ]:
print(((((12+7)*2)-4)/2)-13)

4.0


In [ ]:
print(5 + 5 / 5)

6.0


In [ ]:
print(2 * 5 // 4)

2


In [ ]:
print(2 ** 3 ** 2)

512


In [ ]:
print((2 ** 3) ** 2)

64
